[project]
name = "Alpin-Ide"
version = "0.1.0"
description = "This is a custom ide that I will be writing, because I want to use something 
that I know I can trust and so should you! "
main_script = "./src/main.py"

[packages]
PyQt5 = "5.15.7"
QScintilla = "2.13.3"
jedi = "0.18.1"

[scripts]
build-qrc = "pyrcc5 ./src/icons/resouces.qrc -o ./src/resources.py"
upgrade-pip = "python -m pip install --upgrade pip"